<?php
require_once 'PHPUnit/Framework.php';

require_once 'C:\wamp\www\NewSDK\Invoicing\invoicing-php-sdk\lib\services\Invoice\Invoice.php';

/**
 * Test class for CreateAndSendInvoiceRequest.
 * Generated by PHPUnit on 2011-05-23 at 14:14:59.
 */
class CreateAndSendInvoiceRequestTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var CreateAndSendInvoiceRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CreateAndSendInvoiceRequest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testToNVPString().
     */
    public function testToNVPString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
