<?php
require_once 'PHPUnit/Framework.php';

require_once 'C:\wamp\www\NewSDK\Invoicing\invoicing-php-sdk\lib\services\Invoice\Invoice.php';

/**
 * Test class for ErrorData.
 * Generated by PHPUnit on 2011-05-23 at 14:16:05.
 */
class ErrorDataTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ErrorData
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ErrorData;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
