<?php
require_once 'PHPUnit/Framework.php';

require_once 'C:\wamp\www\NewSDK\Invoicing\invoicing-php-sdk\lib\services\Invoice\InvoiceService.php';

/**
 * Test class for InvoiceService.
 * Generated by PHPUnit on 2011-05-23 at 14:21:06.
 */
class InvoiceServiceTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var InvoiceService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new InvoiceService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testCreateInvoice().
     */
    public function testCreateInvoice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSendInvoice().
     */
    public function testSendInvoice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCreateAndSendInvoice().
     */
    public function testCreateAndSendInvoice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
